-- The ingest queue and the evidence chain's project pairing (ticket 04).
--
-- Generated by drizzle-kit, then hand-ordered: the two new NOT NULL columns
-- backfill from their parents before the constraint lands, and pre-existing
-- succeeded ingests — whose artifacts predate the unsupported_by_type counter
-- — are demoted to a named failure rather than backfilled with an invented
-- empty counter block (cad-ingestion.md §3: counters are the artifact's own).

CREATE TABLE "ingest_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"ingest_id" uuid NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"locked_at" timestamp with time zone,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ingest_jobs_ingest_uq" UNIQUE("ingest_id"),
	CONSTRAINT "ingest_jobs_status_ck" CHECK ("status" in ('queued', 'running', 'succeeded', 'failed')),
	CONSTRAINT "ingest_jobs_failed_ck" CHECK ("status" <> 'failed' or "error" is not null),
	CONSTRAINT "ingest_jobs_attempts_ck" CHECK ("attempts" >= 0)
);
--> statement-breakpoint
ALTER TABLE "ingests" DROP CONSTRAINT "ingests_status_ck";--> statement-breakpoint
ALTER TABLE "ingests" DROP CONSTRAINT "ingests_succeeded_ck";--> statement-breakpoint
ALTER TABLE "refused_sightings" DROP CONSTRAINT "refused_sightings_ingest_tenant_fk";
--> statement-breakpoint
ALTER TABLE "drawing_revisions" ADD COLUMN "project_id" uuid;--> statement-breakpoint
UPDATE "drawing_revisions" r SET "project_id" = d."project_id"
  FROM "drawings" d WHERE d."id" = r."drawing_id";--> statement-breakpoint
ALTER TABLE "drawing_revisions" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ingests" ADD COLUMN "project_id" uuid;--> statement-breakpoint
UPDATE "ingests" i SET "project_id" = r."project_id"
  FROM "drawing_revisions" r WHERE r."id" = i."drawing_revision_id";--> statement-breakpoint
ALTER TABLE "ingests" ALTER COLUMN "project_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ingests" ADD COLUMN "unsupported_by_type" jsonb;--> statement-breakpoint
UPDATE "ingests" SET
    "status" = 'failed',
    "error" = 'ingest predates the unsupported_by_type counter (migration 0006): re-ingest this revision',
    "artifact_ref" = NULL,
    "artifact_sha256" = NULL,
    "entities_original" = NULL,
    "entities_derived" = NULL,
    "explode_truncated" = NULL,
    "lost_by_type" = NULL,
    "insunits" = NULL,
    "unit_detected" = NULL,
    "insunits_unmapped" = NULL
  WHERE "status" = 'succeeded';--> statement-breakpoint
ALTER TABLE "ingest_jobs" ADD CONSTRAINT "ingest_jobs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingest_jobs" ADD CONSTRAINT "ingest_jobs_project_tenant_fk" FOREIGN KEY ("project_id","tenant_id") REFERENCES "public"."projects"("id","tenant_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ingest_jobs_claim_idx" ON "ingest_jobs" USING btree ("status","created_at");--> statement-breakpoint
ALTER TABLE "drawings" ADD CONSTRAINT "drawings_id_project_uq" UNIQUE("id","project_id");--> statement-breakpoint
ALTER TABLE "drawing_revisions" ADD CONSTRAINT "drawing_revisions_id_project_uq" UNIQUE("id","project_id");--> statement-breakpoint
ALTER TABLE "ingests" ADD CONSTRAINT "ingests_id_project_uq" UNIQUE("id","project_id");--> statement-breakpoint
ALTER TABLE "drawing_revisions" ADD CONSTRAINT "drawing_revisions_drawing_project_fk" FOREIGN KEY ("drawing_id","project_id") REFERENCES "public"."drawings"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingests" ADD CONSTRAINT "ingests_revision_project_fk" FOREIGN KEY ("drawing_revision_id","project_id") REFERENCES "public"."drawing_revisions"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingest_jobs" ADD CONSTRAINT "ingest_jobs_ingest_project_fk" FOREIGN KEY ("ingest_id","project_id") REFERENCES "public"."ingests"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refused_sightings" ADD CONSTRAINT "refused_sightings_ingest_project_fk" FOREIGN KEY ("ingest_id","project_id") REFERENCES "public"."ingests"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingests" ADD CONSTRAINT "ingests_status_ck" CHECK ("status" in ('pending', 'running', 'succeeded', 'failed'));--> statement-breakpoint
ALTER TABLE "ingests" ADD CONSTRAINT "ingests_succeeded_ck" CHECK ("status" <> 'succeeded' or ("artifact_ref" is not null and "artifact_sha256" is not null and "entities_original" is not null and "entities_derived" is not null and "explode_truncated" is not null and "lost_by_type" is not null and "unsupported_by_type" is not null and "insunits_unmapped" is not null and "error" is null));
